// Generated by the Protocol Buffers 3.0 compiler.  DO NOT EDIT!
// Source file "POGOProtos.Data.Logs.proto"
// Syntax "Proto3"

import Foundation
import ProtocolBuffers


public func == (lhs: Pogoprotos.Data.Logs.ActionLogEntry, rhs: Pogoprotos.Data.Logs.ActionLogEntry) -> Bool {
  if (lhs === rhs) {
    return true
  }
  var fieldCheck:Bool = (lhs.hashValue == rhs.hashValue)
  fieldCheck = fieldCheck && (lhs.hasTimestampMs == rhs.hasTimestampMs) && (!lhs.hasTimestampMs || lhs.timestampMs == rhs.timestampMs)
  fieldCheck = fieldCheck && (lhs.hasSfida == rhs.hasSfida) && (!lhs.hasSfida || lhs.sfida == rhs.sfida)
  fieldCheck = fieldCheck && (lhs.hasCatchPokemon == rhs.hasCatchPokemon) && (!lhs.hasCatchPokemon || lhs.catchPokemon == rhs.catchPokemon)
  fieldCheck = fieldCheck && (lhs.hasFortSearch == rhs.hasFortSearch) && (!lhs.hasFortSearch || lhs.fortSearch == rhs.fortSearch)
  fieldCheck = (fieldCheck && (lhs.unknownFields == rhs.unknownFields))
  return fieldCheck
}

public func == (lhs: Pogoprotos.Data.Logs.CatchPokemonLogEntry, rhs: Pogoprotos.Data.Logs.CatchPokemonLogEntry) -> Bool {
  if (lhs === rhs) {
    return true
  }
  var fieldCheck:Bool = (lhs.hashValue == rhs.hashValue)
  fieldCheck = fieldCheck && (lhs.hasResult == rhs.hasResult) && (!lhs.hasResult || lhs.result == rhs.result)
  fieldCheck = fieldCheck && (lhs.hasPokemonId == rhs.hasPokemonId) && (!lhs.hasPokemonId || lhs.pokemonId == rhs.pokemonId)
  fieldCheck = fieldCheck && (lhs.hasCombatPoints == rhs.hasCombatPoints) && (!lhs.hasCombatPoints || lhs.combatPoints == rhs.combatPoints)
  fieldCheck = fieldCheck && (lhs.hasPokemonDataId == rhs.hasPokemonDataId) && (!lhs.hasPokemonDataId || lhs.pokemonDataId == rhs.pokemonDataId)
  fieldCheck = (fieldCheck && (lhs.unknownFields == rhs.unknownFields))
  return fieldCheck
}

public func == (lhs: Pogoprotos.Data.Logs.FortSearchLogEntry, rhs: Pogoprotos.Data.Logs.FortSearchLogEntry) -> Bool {
  if (lhs === rhs) {
    return true
  }
  var fieldCheck:Bool = (lhs.hashValue == rhs.hashValue)
  fieldCheck = fieldCheck && (lhs.hasResult == rhs.hasResult) && (!lhs.hasResult || lhs.result == rhs.result)
  fieldCheck = fieldCheck && (lhs.hasFortId == rhs.hasFortId) && (!lhs.hasFortId || lhs.fortId == rhs.fortId)
  fieldCheck = fieldCheck && (lhs.items == rhs.items)
  fieldCheck = fieldCheck && (lhs.hasEggs == rhs.hasEggs) && (!lhs.hasEggs || lhs.eggs == rhs.eggs)
  fieldCheck = (fieldCheck && (lhs.unknownFields == rhs.unknownFields))
  return fieldCheck
}

public extension Pogoprotos.Data.Logs {
  public struct PogoprotosDataLogsRoot {
    public static var sharedInstance : PogoprotosDataLogsRoot {
     struct Static {
         static let instance : PogoprotosDataLogsRoot = PogoprotosDataLogsRoot()
     }
     return Static.instance
    }
    public var extensionRegistry:ExtensionRegistry

    init() {
      extensionRegistry = ExtensionRegistry()
      registerAllExtensions(extensionRegistry)
      Pogoprotos.Enums.PogoprotosEnumsRoot.sharedInstance.registerAllExtensions(extensionRegistry)
      Pogoprotos.Inventory.Item.PogoprotosInventoryItemRoot.sharedInstance.registerAllExtensions(extensionRegistry)
    }
    public func registerAllExtensions(registry:ExtensionRegistry) {
    }
  }

  final public class ActionLogEntry : GeneratedMessage, GeneratedMessageProtocol {


    //OneOf declaration start

    public enum Action {
      case OneOfActionNotSet

      public func checkOneOfIsSet() -> Bool {
           switch self {
           case .OneOfActionNotSet:
                return false
           default:
                return true
           }
      }
      case CatchPokemon(Pogoprotos.Data.Logs.CatchPokemonLogEntry)

      public static func getCatchPokemon(value:Action) -> Pogoprotos.Data.Logs.CatchPokemonLogEntry? {
           switch value {
           case .CatchPokemon(let enumValue):
                return enumValue
           default:
                return nil
           }
      }
      case FortSearch(Pogoprotos.Data.Logs.FortSearchLogEntry)

      public static func getFortSearch(value:Action) -> Pogoprotos.Data.Logs.FortSearchLogEntry? {
           switch value {
           case .FortSearch(let enumValue):
                return enumValue
           default:
                return nil
           }
      }
    }
    //OneOf declaration end

    private var storageAction:ActionLogEntry.Action =  ActionLogEntry.Action.OneOfActionNotSet
    public func getOneOfAction() ->  ActionLogEntry.Action {
        let copyObjectAction = storageAction
        return copyObjectAction
    }
    public private(set) var hasTimestampMs:Bool = false
    public private(set) var timestampMs:Int64 = Int64(0)

    public private(set) var hasSfida:Bool = false
    public private(set) var sfida:Bool = false

    public private(set) var hasCatchPokemon:Bool {
          get {
                guard let _ = ActionLogEntry.Action.getCatchPokemon(storageAction) else {
                    return false
                }
                return true
          }
          set(newValue) {
          }
    }
    public private(set) var catchPokemon:Pogoprotos.Data.Logs.CatchPokemonLogEntry!{
         get {
              return ActionLogEntry.Action.getCatchPokemon(storageAction)
         }
         set (newvalue) {
              storageAction = ActionLogEntry.Action.CatchPokemon(newvalue)
         }
    }
    public private(set) var hasFortSearch:Bool {
          get {
                guard let _ = ActionLogEntry.Action.getFortSearch(storageAction) else {
                    return false
                }
                return true
          }
          set(newValue) {
          }
    }
    public private(set) var fortSearch:Pogoprotos.Data.Logs.FortSearchLogEntry!{
         get {
              return ActionLogEntry.Action.getFortSearch(storageAction)
         }
         set (newvalue) {
              storageAction = ActionLogEntry.Action.FortSearch(newvalue)
         }
    }
    required public init() {
         super.init()
    }
    override public func isInitialized() -> Bool {
     return true
    }
    override public func writeToCodedOutputStream(output:CodedOutputStream) throws {
      if hasTimestampMs {
        try output.writeInt64(1, value:timestampMs)
      }
      if hasSfida {
        try output.writeBool(2, value:sfida)
      }
      if hasCatchPokemon {
        try output.writeMessage(3, value:catchPokemon)
      }
      if hasFortSearch {
        try output.writeMessage(4, value:fortSearch)
      }
      try unknownFields.writeToCodedOutputStream(output)
    }
    override public func serializedSize() -> Int32 {
      var serialize_size:Int32 = memoizedSerializedSize
      if serialize_size != -1 {
       return serialize_size
      }

      serialize_size = 0
      if hasTimestampMs {
        serialize_size += timestampMs.computeInt64Size(1)
      }
      if hasSfida {
        serialize_size += sfida.computeBoolSize(2)
      }
      if hasCatchPokemon {
          if let varSizecatchPokemon = catchPokemon?.computeMessageSize(3) {
              serialize_size += varSizecatchPokemon
          }
      }
      if hasFortSearch {
          if let varSizefortSearch = fortSearch?.computeMessageSize(4) {
              serialize_size += varSizefortSearch
          }
      }
      serialize_size += unknownFields.serializedSize()
      memoizedSerializedSize = serialize_size
      return serialize_size
    }
    public class func parseArrayDelimitedFromInputStream(input:NSInputStream) throws -> Array<Pogoprotos.Data.Logs.ActionLogEntry> {
      var mergedArray = Array<Pogoprotos.Data.Logs.ActionLogEntry>()
      while let value = try parseFromDelimitedFromInputStream(input) {
        mergedArray += [value]
      }
      return mergedArray
    }
    public class func parseFromDelimitedFromInputStream(input:NSInputStream) throws -> Pogoprotos.Data.Logs.ActionLogEntry? {
      return try Pogoprotos.Data.Logs.ActionLogEntry.Builder().mergeDelimitedFromInputStream(input)?.build()
    }
    public class func parseFromData(data:NSData) throws -> Pogoprotos.Data.Logs.ActionLogEntry {
      return try Pogoprotos.Data.Logs.ActionLogEntry.Builder().mergeFromData(data, extensionRegistry:Pogoprotos.Data.Logs.PogoprotosDataLogsRoot.sharedInstance.extensionRegistry).build()
    }
    public class func parseFromData(data:NSData, extensionRegistry:ExtensionRegistry) throws -> Pogoprotos.Data.Logs.ActionLogEntry {
      return try Pogoprotos.Data.Logs.ActionLogEntry.Builder().mergeFromData(data, extensionRegistry:extensionRegistry).build()
    }
    public class func parseFromInputStream(input:NSInputStream) throws -> Pogoprotos.Data.Logs.ActionLogEntry {
      return try Pogoprotos.Data.Logs.ActionLogEntry.Builder().mergeFromInputStream(input).build()
    }
    public class func parseFromInputStream(input:NSInputStream, extensionRegistry:ExtensionRegistry) throws -> Pogoprotos.Data.Logs.ActionLogEntry {
      return try Pogoprotos.Data.Logs.ActionLogEntry.Builder().mergeFromInputStream(input, extensionRegistry:extensionRegistry).build()
    }
    public class func parseFromCodedInputStream(input:CodedInputStream) throws -> Pogoprotos.Data.Logs.ActionLogEntry {
      return try Pogoprotos.Data.Logs.ActionLogEntry.Builder().mergeFromCodedInputStream(input).build()
    }
    public class func parseFromCodedInputStream(input:CodedInputStream, extensionRegistry:ExtensionRegistry) throws -> Pogoprotos.Data.Logs.ActionLogEntry {
      return try Pogoprotos.Data.Logs.ActionLogEntry.Builder().mergeFromCodedInputStream(input, extensionRegistry:extensionRegistry).build()
    }
    public class func getBuilder() -> Pogoprotos.Data.Logs.ActionLogEntry.Builder {
      return Pogoprotos.Data.Logs.ActionLogEntry.classBuilder() as! Pogoprotos.Data.Logs.ActionLogEntry.Builder
    }
    public func getBuilder() -> Pogoprotos.Data.Logs.ActionLogEntry.Builder {
      return classBuilder() as! Pogoprotos.Data.Logs.ActionLogEntry.Builder
    }
    override public class func classBuilder() -> MessageBuilder {
      return Pogoprotos.Data.Logs.ActionLogEntry.Builder()
    }
    override public func classBuilder() -> MessageBuilder {
      return Pogoprotos.Data.Logs.ActionLogEntry.Builder()
    }
    public func toBuilder() throws -> Pogoprotos.Data.Logs.ActionLogEntry.Builder {
      return try Pogoprotos.Data.Logs.ActionLogEntry.builderWithPrototype(self)
    }
    public class func builderWithPrototype(prototype:Pogoprotos.Data.Logs.ActionLogEntry) throws -> Pogoprotos.Data.Logs.ActionLogEntry.Builder {
      return try Pogoprotos.Data.Logs.ActionLogEntry.Builder().mergeFrom(prototype)
    }
    override public func encode() throws -> Dictionary<String,AnyObject> {
      guard isInitialized() else {
        throw ProtocolBuffersError.InvalidProtocolBuffer("Uninitialized Message")
      }

      var jsonMap:Dictionary<String,AnyObject> = Dictionary<String,AnyObject>()
      if hasTimestampMs {
        jsonMap["timestampMs"] = "\(timestampMs)"
      }
      if hasSfida {
        jsonMap["sfida"] = sfida
      }
      if hasCatchPokemon {
        jsonMap["catchPokemon"] = try catchPokemon.encode()
      }
      if hasFortSearch {
        jsonMap["fortSearch"] = try fortSearch.encode()
      }
      return jsonMap
    }
    override class public func decode(jsonMap:Dictionary<String,AnyObject>) throws -> Pogoprotos.Data.Logs.ActionLogEntry {
      return try Pogoprotos.Data.Logs.ActionLogEntry.Builder.decodeToBuilder(jsonMap).build()
    }
    override class public func fromJSON(data:NSData) throws -> Pogoprotos.Data.Logs.ActionLogEntry {
      return try Pogoprotos.Data.Logs.ActionLogEntry.Builder.fromJSONToBuilder(data).build()
    }
    override public func getDescription(indent:String) throws -> String {
      var output = ""
      if hasTimestampMs {
        output += "\(indent) timestampMs: \(timestampMs) \n"
      }
      if hasSfida {
        output += "\(indent) sfida: \(sfida) \n"
      }
      if hasCatchPokemon {
        output += "\(indent) catchPokemon {\n"
        if let outDescCatchPokemon = catchPokemon {
          output += try outDescCatchPokemon.getDescription("\(indent)  ")
        }
        output += "\(indent) }\n"
      }
      if hasFortSearch {
        output += "\(indent) fortSearch {\n"
        if let outDescFortSearch = fortSearch {
          output += try outDescFortSearch.getDescription("\(indent)  ")
        }
        output += "\(indent) }\n"
      }
      output += unknownFields.getDescription(indent)
      return output
    }
    override public var hashValue:Int {
        get {
            var hashCode:Int = 7
            if hasTimestampMs {
               hashCode = (hashCode &* 31) &+ timestampMs.hashValue
            }
            if hasSfida {
               hashCode = (hashCode &* 31) &+ sfida.hashValue
            }
            if hasCatchPokemon {
                if let hashValuecatchPokemon = catchPokemon?.hashValue {
                    hashCode = (hashCode &* 31) &+ hashValuecatchPokemon
                }
            }
            if hasFortSearch {
                if let hashValuefortSearch = fortSearch?.hashValue {
                    hashCode = (hashCode &* 31) &+ hashValuefortSearch
                }
            }
            hashCode = (hashCode &* 31) &+  unknownFields.hashValue
            return hashCode
        }
    }


    //Meta information declaration start

    override public class func className() -> String {
        return "Pogoprotos.Data.Logs.ActionLogEntry"
    }
    override public func className() -> String {
        return "Pogoprotos.Data.Logs.ActionLogEntry"
    }
    override public func classMetaType() -> GeneratedMessage.Type {
        return Pogoprotos.Data.Logs.ActionLogEntry.self
    }
    //Meta information declaration end

    final public class Builder : GeneratedMessageBuilder {
      private var builderResult:Pogoprotos.Data.Logs.ActionLogEntry = Pogoprotos.Data.Logs.ActionLogEntry()
      public func getMessage() -> Pogoprotos.Data.Logs.ActionLogEntry {
          return builderResult
      }

      required override public init () {
         super.init()
      }
      public var hasTimestampMs:Bool {
           get {
                return builderResult.hasTimestampMs
           }
      }
      public var timestampMs:Int64 {
           get {
                return builderResult.timestampMs
           }
           set (value) {
               builderResult.hasTimestampMs = true
               builderResult.timestampMs = value
           }
      }
      public func setTimestampMs(value:Int64) -> Pogoprotos.Data.Logs.ActionLogEntry.Builder {
        self.timestampMs = value
        return self
      }
      public func clearTimestampMs() -> Pogoprotos.Data.Logs.ActionLogEntry.Builder{
           builderResult.hasTimestampMs = false
           builderResult.timestampMs = Int64(0)
           return self
      }
      public var hasSfida:Bool {
           get {
                return builderResult.hasSfida
           }
      }
      public var sfida:Bool {
           get {
                return builderResult.sfida
           }
           set (value) {
               builderResult.hasSfida = true
               builderResult.sfida = value
           }
      }
      public func setSfida(value:Bool) -> Pogoprotos.Data.Logs.ActionLogEntry.Builder {
        self.sfida = value
        return self
      }
      public func clearSfida() -> Pogoprotos.Data.Logs.ActionLogEntry.Builder{
           builderResult.hasSfida = false
           builderResult.sfida = false
           return self
      }
      public var hasCatchPokemon:Bool {
           get {
               return builderResult.hasCatchPokemon
           }
      }
      public var catchPokemon:Pogoprotos.Data.Logs.CatchPokemonLogEntry! {
           get {
               if catchPokemonBuilder_ != nil {
                  builderResult.catchPokemon = catchPokemonBuilder_.getMessage()
               }
               return builderResult.catchPokemon
           }
           set (value) {
               builderResult.hasCatchPokemon = true
               builderResult.catchPokemon = value
           }
      }
      private var catchPokemonBuilder_:Pogoprotos.Data.Logs.CatchPokemonLogEntry.Builder! {
           didSet {
              builderResult.hasCatchPokemon = true
           }
      }
      public func getCatchPokemonBuilder() -> Pogoprotos.Data.Logs.CatchPokemonLogEntry.Builder {
        if catchPokemonBuilder_ == nil {
           catchPokemonBuilder_ = Pogoprotos.Data.Logs.CatchPokemonLogEntry.Builder()
           builderResult.catchPokemon = catchPokemonBuilder_.getMessage()
           if catchPokemon != nil {
              try! catchPokemonBuilder_.mergeFrom(catchPokemon)
           }
        }
        return catchPokemonBuilder_
      }
      public func setCatchPokemon(value:Pogoprotos.Data.Logs.CatchPokemonLogEntry!) -> Pogoprotos.Data.Logs.ActionLogEntry.Builder {
        self.catchPokemon = value
        return self
      }
      public func mergeCatchPokemon(value:Pogoprotos.Data.Logs.CatchPokemonLogEntry) throws -> Pogoprotos.Data.Logs.ActionLogEntry.Builder {
        if builderResult.hasCatchPokemon {
          builderResult.catchPokemon = try Pogoprotos.Data.Logs.CatchPokemonLogEntry.builderWithPrototype(builderResult.catchPokemon).mergeFrom(value).buildPartial()
        } else {
          builderResult.catchPokemon = value
        }
        builderResult.hasCatchPokemon = true
        return self
      }
      public func clearCatchPokemon() -> Pogoprotos.Data.Logs.ActionLogEntry.Builder {
        catchPokemonBuilder_ = nil
        builderResult.hasCatchPokemon = false
        builderResult.catchPokemon = nil
        return self
      }
      public var hasFortSearch:Bool {
           get {
               return builderResult.hasFortSearch
           }
      }
      public var fortSearch:Pogoprotos.Data.Logs.FortSearchLogEntry! {
           get {
               if fortSearchBuilder_ != nil {
                  builderResult.fortSearch = fortSearchBuilder_.getMessage()
               }
               return builderResult.fortSearch
           }
           set (value) {
               builderResult.hasFortSearch = true
               builderResult.fortSearch = value
           }
      }
      private var fortSearchBuilder_:Pogoprotos.Data.Logs.FortSearchLogEntry.Builder! {
           didSet {
              builderResult.hasFortSearch = true
           }
      }
      public func getFortSearchBuilder() -> Pogoprotos.Data.Logs.FortSearchLogEntry.Builder {
        if fortSearchBuilder_ == nil {
           fortSearchBuilder_ = Pogoprotos.Data.Logs.FortSearchLogEntry.Builder()
           builderResult.fortSearch = fortSearchBuilder_.getMessage()
           if fortSearch != nil {
              try! fortSearchBuilder_.mergeFrom(fortSearch)
           }
        }
        return fortSearchBuilder_
      }
      public func setFortSearch(value:Pogoprotos.Data.Logs.FortSearchLogEntry!) -> Pogoprotos.Data.Logs.ActionLogEntry.Builder {
        self.fortSearch = value
        return self
      }
      public func mergeFortSearch(value:Pogoprotos.Data.Logs.FortSearchLogEntry) throws -> Pogoprotos.Data.Logs.ActionLogEntry.Builder {
        if builderResult.hasFortSearch {
          builderResult.fortSearch = try Pogoprotos.Data.Logs.FortSearchLogEntry.builderWithPrototype(builderResult.fortSearch).mergeFrom(value).buildPartial()
        } else {
          builderResult.fortSearch = value
        }
        builderResult.hasFortSearch = true
        return self
      }
      public func clearFortSearch() -> Pogoprotos.Data.Logs.ActionLogEntry.Builder {
        fortSearchBuilder_ = nil
        builderResult.hasFortSearch = false
        builderResult.fortSearch = nil
        return self
      }
      override public var internalGetResult:GeneratedMessage {
           get {
              return builderResult
           }
      }
      override public func clear() -> Pogoprotos.Data.Logs.ActionLogEntry.Builder {
        builderResult = Pogoprotos.Data.Logs.ActionLogEntry()
        return self
      }
      override public func clone() throws -> Pogoprotos.Data.Logs.ActionLogEntry.Builder {
        return try Pogoprotos.Data.Logs.ActionLogEntry.builderWithPrototype(builderResult)
      }
      override public func build() throws -> Pogoprotos.Data.Logs.ActionLogEntry {
           try checkInitialized()
           return buildPartial()
      }
      public func buildPartial() -> Pogoprotos.Data.Logs.ActionLogEntry {
        let returnMe:Pogoprotos.Data.Logs.ActionLogEntry = builderResult
        return returnMe
      }
      public func mergeFrom(other:Pogoprotos.Data.Logs.ActionLogEntry) throws -> Pogoprotos.Data.Logs.ActionLogEntry.Builder {
        if other == Pogoprotos.Data.Logs.ActionLogEntry() {
         return self
        }
        if other.hasTimestampMs {
             timestampMs = other.timestampMs
        }
        if other.hasSfida {
             sfida = other.sfida
        }
        if (other.hasCatchPokemon) {
            try mergeCatchPokemon(other.catchPokemon)
        }
        if (other.hasFortSearch) {
            try mergeFortSearch(other.fortSearch)
        }
        try mergeUnknownFields(other.unknownFields)
        return self
      }
      override public func mergeFromCodedInputStream(input:CodedInputStream) throws -> Pogoprotos.Data.Logs.ActionLogEntry.Builder {
           return try mergeFromCodedInputStream(input, extensionRegistry:ExtensionRegistry())
      }
      override public func mergeFromCodedInputStream(input:CodedInputStream, extensionRegistry:ExtensionRegistry) throws -> Pogoprotos.Data.Logs.ActionLogEntry.Builder {
        let unknownFieldsBuilder:UnknownFieldSet.Builder = try UnknownFieldSet.builderWithUnknownFields(self.unknownFields)
        while (true) {
          let protobufTag = try input.readTag()
          switch protobufTag {
          case 0: 
            self.unknownFields = try unknownFieldsBuilder.build()
            return self

          case 8:
            timestampMs = try input.readInt64()

          case 16:
            sfida = try input.readBool()

          case 26:
            let subBuilder:Pogoprotos.Data.Logs.CatchPokemonLogEntry.Builder = Pogoprotos.Data.Logs.CatchPokemonLogEntry.Builder()
            if hasCatchPokemon {
              try subBuilder.mergeFrom(catchPokemon)
            }
            try input.readMessage(subBuilder, extensionRegistry:extensionRegistry)
            catchPokemon = subBuilder.buildPartial()

          case 34:
            let subBuilder:Pogoprotos.Data.Logs.FortSearchLogEntry.Builder = Pogoprotos.Data.Logs.FortSearchLogEntry.Builder()
            if hasFortSearch {
              try subBuilder.mergeFrom(fortSearch)
            }
            try input.readMessage(subBuilder, extensionRegistry:extensionRegistry)
            fortSearch = subBuilder.buildPartial()

          default:
            if (!(try parseUnknownField(input,unknownFields:unknownFieldsBuilder, extensionRegistry:extensionRegistry, tag:protobufTag))) {
               unknownFields = try unknownFieldsBuilder.build()
               return self
            }
          }
        }
      }
      override class public func decodeToBuilder(jsonMap:Dictionary<String,AnyObject>) throws -> Pogoprotos.Data.Logs.ActionLogEntry.Builder {
        let resultDecodedBuilder = Pogoprotos.Data.Logs.ActionLogEntry.Builder()
        if let jsonValueTimestampMs = jsonMap["timestampMs"] as? String {
          resultDecodedBuilder.timestampMs = Int64(jsonValueTimestampMs)!
        }
        if let jsonValueSfida = jsonMap["sfida"] as? Bool {
          resultDecodedBuilder.sfida = jsonValueSfida
        }
        if let jsonValueCatchPokemon = jsonMap["catchPokemon"] as? Dictionary<String,AnyObject> {
          resultDecodedBuilder.catchPokemon = try Pogoprotos.Data.Logs.CatchPokemonLogEntry.Builder.decodeToBuilder(jsonValueCatchPokemon).build()

        }
        if let jsonValueFortSearch = jsonMap["fortSearch"] as? Dictionary<String,AnyObject> {
          resultDecodedBuilder.fortSearch = try Pogoprotos.Data.Logs.FortSearchLogEntry.Builder.decodeToBuilder(jsonValueFortSearch).build()

        }
        return resultDecodedBuilder
      }
      override class public func fromJSONToBuilder(data:NSData) throws -> Pogoprotos.Data.Logs.ActionLogEntry.Builder {
        let jsonData = try NSJSONSerialization.JSONObjectWithData(data, options: NSJSONReadingOptions(rawValue: 0))
        guard let jsDataCast = jsonData as? Dictionary<String,AnyObject> else {
          throw ProtocolBuffersError.InvalidProtocolBuffer("Invalid JSON data")
        }
        return try Pogoprotos.Data.Logs.ActionLogEntry.Builder.decodeToBuilder(jsDataCast)
      }
    }

  }

  final public class CatchPokemonLogEntry : GeneratedMessage, GeneratedMessageProtocol {


      //Enum type declaration start 

      public enum Result:Int32, CustomDebugStringConvertible, CustomStringConvertible {
        case Unset = 0
        case PokemonCaptured = 1
        case PokemonFled = 2
        public func toString() -> String {
          switch self {
          case .Unset: return "UNSET"
          case .PokemonCaptured: return "POKEMON_CAPTURED"
          case .PokemonFled: return "POKEMON_FLED"
          }
        }
        public static func fromString(str:String) throws -> Pogoprotos.Data.Logs.CatchPokemonLogEntry.Result {
          switch str {
          case "UNSET":  return .Unset
          case "POKEMON_CAPTURED":  return .PokemonCaptured
          case "POKEMON_FLED":  return .PokemonFled
          default: throw ProtocolBuffersError.InvalidProtocolBuffer("Conversion String to Enum has failed.")
          }
        }
        public var debugDescription:String { return getDescription() }
        public var description:String { return getDescription() }
        private func getDescription() -> String { 
            switch self {
                case .Unset: return ".Unset"
                case .PokemonCaptured: return ".PokemonCaptured"
                case .PokemonFled: return ".PokemonFled"
            }
        }
      }

      //Enum type declaration end 

    public private(set) var result:Pogoprotos.Data.Logs.CatchPokemonLogEntry.Result = Pogoprotos.Data.Logs.CatchPokemonLogEntry.Result.Unset
    public private(set) var hasResult:Bool = false
    public private(set) var pokemonId:Pogoprotos.Enums.PokemonId = Pogoprotos.Enums.PokemonId.Missingno
    public private(set) var hasPokemonId:Bool = false
    public private(set) var hasCombatPoints:Bool = false
    public private(set) var combatPoints:Int32 = Int32(0)

    public private(set) var hasPokemonDataId:Bool = false
    public private(set) var pokemonDataId:UInt64 = UInt64(0)

    required public init() {
         super.init()
    }
    override public func isInitialized() -> Bool {
     return true
    }
    override public func writeToCodedOutputStream(output:CodedOutputStream) throws {
      if hasResult {
        try output.writeEnum(1, value:result.rawValue)
      }
      if hasPokemonId {
        try output.writeEnum(2, value:pokemonId.rawValue)
      }
      if hasCombatPoints {
        try output.writeInt32(3, value:combatPoints)
      }
      if hasPokemonDataId {
        try output.writeUInt64(4, value:pokemonDataId)
      }
      try unknownFields.writeToCodedOutputStream(output)
    }
    override public func serializedSize() -> Int32 {
      var serialize_size:Int32 = memoizedSerializedSize
      if serialize_size != -1 {
       return serialize_size
      }

      serialize_size = 0
      if (hasResult) {
        serialize_size += result.rawValue.computeEnumSize(1)
      }
      if (hasPokemonId) {
        serialize_size += pokemonId.rawValue.computeEnumSize(2)
      }
      if hasCombatPoints {
        serialize_size += combatPoints.computeInt32Size(3)
      }
      if hasPokemonDataId {
        serialize_size += pokemonDataId.computeUInt64Size(4)
      }
      serialize_size += unknownFields.serializedSize()
      memoizedSerializedSize = serialize_size
      return serialize_size
    }
    public class func parseArrayDelimitedFromInputStream(input:NSInputStream) throws -> Array<Pogoprotos.Data.Logs.CatchPokemonLogEntry> {
      var mergedArray = Array<Pogoprotos.Data.Logs.CatchPokemonLogEntry>()
      while let value = try parseFromDelimitedFromInputStream(input) {
        mergedArray += [value]
      }
      return mergedArray
    }
    public class func parseFromDelimitedFromInputStream(input:NSInputStream) throws -> Pogoprotos.Data.Logs.CatchPokemonLogEntry? {
      return try Pogoprotos.Data.Logs.CatchPokemonLogEntry.Builder().mergeDelimitedFromInputStream(input)?.build()
    }
    public class func parseFromData(data:NSData) throws -> Pogoprotos.Data.Logs.CatchPokemonLogEntry {
      return try Pogoprotos.Data.Logs.CatchPokemonLogEntry.Builder().mergeFromData(data, extensionRegistry:Pogoprotos.Data.Logs.PogoprotosDataLogsRoot.sharedInstance.extensionRegistry).build()
    }
    public class func parseFromData(data:NSData, extensionRegistry:ExtensionRegistry) throws -> Pogoprotos.Data.Logs.CatchPokemonLogEntry {
      return try Pogoprotos.Data.Logs.CatchPokemonLogEntry.Builder().mergeFromData(data, extensionRegistry:extensionRegistry).build()
    }
    public class func parseFromInputStream(input:NSInputStream) throws -> Pogoprotos.Data.Logs.CatchPokemonLogEntry {
      return try Pogoprotos.Data.Logs.CatchPokemonLogEntry.Builder().mergeFromInputStream(input).build()
    }
    public class func parseFromInputStream(input:NSInputStream, extensionRegistry:ExtensionRegistry) throws -> Pogoprotos.Data.Logs.CatchPokemonLogEntry {
      return try Pogoprotos.Data.Logs.CatchPokemonLogEntry.Builder().mergeFromInputStream(input, extensionRegistry:extensionRegistry).build()
    }
    public class func parseFromCodedInputStream(input:CodedInputStream) throws -> Pogoprotos.Data.Logs.CatchPokemonLogEntry {
      return try Pogoprotos.Data.Logs.CatchPokemonLogEntry.Builder().mergeFromCodedInputStream(input).build()
    }
    public class func parseFromCodedInputStream(input:CodedInputStream, extensionRegistry:ExtensionRegistry) throws -> Pogoprotos.Data.Logs.CatchPokemonLogEntry {
      return try Pogoprotos.Data.Logs.CatchPokemonLogEntry.Builder().mergeFromCodedInputStream(input, extensionRegistry:extensionRegistry).build()
    }
    public class func getBuilder() -> Pogoprotos.Data.Logs.CatchPokemonLogEntry.Builder {
      return Pogoprotos.Data.Logs.CatchPokemonLogEntry.classBuilder() as! Pogoprotos.Data.Logs.CatchPokemonLogEntry.Builder
    }
    public func getBuilder() -> Pogoprotos.Data.Logs.CatchPokemonLogEntry.Builder {
      return classBuilder() as! Pogoprotos.Data.Logs.CatchPokemonLogEntry.Builder
    }
    override public class func classBuilder() -> MessageBuilder {
      return Pogoprotos.Data.Logs.CatchPokemonLogEntry.Builder()
    }
    override public func classBuilder() -> MessageBuilder {
      return Pogoprotos.Data.Logs.CatchPokemonLogEntry.Builder()
    }
    public func toBuilder() throws -> Pogoprotos.Data.Logs.CatchPokemonLogEntry.Builder {
      return try Pogoprotos.Data.Logs.CatchPokemonLogEntry.builderWithPrototype(self)
    }
    public class func builderWithPrototype(prototype:Pogoprotos.Data.Logs.CatchPokemonLogEntry) throws -> Pogoprotos.Data.Logs.CatchPokemonLogEntry.Builder {
      return try Pogoprotos.Data.Logs.CatchPokemonLogEntry.Builder().mergeFrom(prototype)
    }
    override public func encode() throws -> Dictionary<String,AnyObject> {
      guard isInitialized() else {
        throw ProtocolBuffersError.InvalidProtocolBuffer("Uninitialized Message")
      }

      var jsonMap:Dictionary<String,AnyObject> = Dictionary<String,AnyObject>()
      if hasResult {
        jsonMap["result"] = result.toString()
      }
      if hasPokemonId {
        jsonMap["pokemonId"] = pokemonId.toString()
      }
      if hasCombatPoints {
        jsonMap["combatPoints"] = NSNumber(int:combatPoints)
      }
      if hasPokemonDataId {
        jsonMap["pokemonDataId"] = "\(pokemonDataId)"
      }
      return jsonMap
    }
    override class public func decode(jsonMap:Dictionary<String,AnyObject>) throws -> Pogoprotos.Data.Logs.CatchPokemonLogEntry {
      return try Pogoprotos.Data.Logs.CatchPokemonLogEntry.Builder.decodeToBuilder(jsonMap).build()
    }
    override class public func fromJSON(data:NSData) throws -> Pogoprotos.Data.Logs.CatchPokemonLogEntry {
      return try Pogoprotos.Data.Logs.CatchPokemonLogEntry.Builder.fromJSONToBuilder(data).build()
    }
    override public func getDescription(indent:String) throws -> String {
      var output = ""
      if (hasResult) {
        output += "\(indent) result: \(result.description)\n"
      }
      if (hasPokemonId) {
        output += "\(indent) pokemonId: \(pokemonId.description)\n"
      }
      if hasCombatPoints {
        output += "\(indent) combatPoints: \(combatPoints) \n"
      }
      if hasPokemonDataId {
        output += "\(indent) pokemonDataId: \(pokemonDataId) \n"
      }
      output += unknownFields.getDescription(indent)
      return output
    }
    override public var hashValue:Int {
        get {
            var hashCode:Int = 7
            if hasResult {
               hashCode = (hashCode &* 31) &+ Int(result.rawValue)
            }
            if hasPokemonId {
               hashCode = (hashCode &* 31) &+ Int(pokemonId.rawValue)
            }
            if hasCombatPoints {
               hashCode = (hashCode &* 31) &+ combatPoints.hashValue
            }
            if hasPokemonDataId {
               hashCode = (hashCode &* 31) &+ pokemonDataId.hashValue
            }
            hashCode = (hashCode &* 31) &+  unknownFields.hashValue
            return hashCode
        }
    }


    //Meta information declaration start

    override public class func className() -> String {
        return "Pogoprotos.Data.Logs.CatchPokemonLogEntry"
    }
    override public func className() -> String {
        return "Pogoprotos.Data.Logs.CatchPokemonLogEntry"
    }
    override public func classMetaType() -> GeneratedMessage.Type {
        return Pogoprotos.Data.Logs.CatchPokemonLogEntry.self
    }
    //Meta information declaration end

    final public class Builder : GeneratedMessageBuilder {
      private var builderResult:Pogoprotos.Data.Logs.CatchPokemonLogEntry = Pogoprotos.Data.Logs.CatchPokemonLogEntry()
      public func getMessage() -> Pogoprotos.Data.Logs.CatchPokemonLogEntry {
          return builderResult
      }

      required override public init () {
         super.init()
      }
        public var hasResult:Bool{
            get {
                return builderResult.hasResult
            }
        }
        public var result:Pogoprotos.Data.Logs.CatchPokemonLogEntry.Result {
            get {
                return builderResult.result
            }
            set (value) {
                builderResult.hasResult = true
                builderResult.result = value
            }
        }
        public func setResult(value:Pogoprotos.Data.Logs.CatchPokemonLogEntry.Result) -> Pogoprotos.Data.Logs.CatchPokemonLogEntry.Builder {
          self.result = value
          return self
        }
        public func clearResult() -> Pogoprotos.Data.Logs.CatchPokemonLogEntry.Builder {
           builderResult.hasResult = false
           builderResult.result = .Unset
           return self
        }
        public var hasPokemonId:Bool{
            get {
                return builderResult.hasPokemonId
            }
        }
        public var pokemonId:Pogoprotos.Enums.PokemonId {
            get {
                return builderResult.pokemonId
            }
            set (value) {
                builderResult.hasPokemonId = true
                builderResult.pokemonId = value
            }
        }
        public func setPokemonId(value:Pogoprotos.Enums.PokemonId) -> Pogoprotos.Data.Logs.CatchPokemonLogEntry.Builder {
          self.pokemonId = value
          return self
        }
        public func clearPokemonId() -> Pogoprotos.Data.Logs.CatchPokemonLogEntry.Builder {
           builderResult.hasPokemonId = false
           builderResult.pokemonId = .Missingno
           return self
        }
      public var hasCombatPoints:Bool {
           get {
                return builderResult.hasCombatPoints
           }
      }
      public var combatPoints:Int32 {
           get {
                return builderResult.combatPoints
           }
           set (value) {
               builderResult.hasCombatPoints = true
               builderResult.combatPoints = value
           }
      }
      public func setCombatPoints(value:Int32) -> Pogoprotos.Data.Logs.CatchPokemonLogEntry.Builder {
        self.combatPoints = value
        return self
      }
      public func clearCombatPoints() -> Pogoprotos.Data.Logs.CatchPokemonLogEntry.Builder{
           builderResult.hasCombatPoints = false
           builderResult.combatPoints = Int32(0)
           return self
      }
      public var hasPokemonDataId:Bool {
           get {
                return builderResult.hasPokemonDataId
           }
      }
      public var pokemonDataId:UInt64 {
           get {
                return builderResult.pokemonDataId
           }
           set (value) {
               builderResult.hasPokemonDataId = true
               builderResult.pokemonDataId = value
           }
      }
      public func setPokemonDataId(value:UInt64) -> Pogoprotos.Data.Logs.CatchPokemonLogEntry.Builder {
        self.pokemonDataId = value
        return self
      }
      public func clearPokemonDataId() -> Pogoprotos.Data.Logs.CatchPokemonLogEntry.Builder{
           builderResult.hasPokemonDataId = false
           builderResult.pokemonDataId = UInt64(0)
           return self
      }
      override public var internalGetResult:GeneratedMessage {
           get {
              return builderResult
           }
      }
      override public func clear() -> Pogoprotos.Data.Logs.CatchPokemonLogEntry.Builder {
        builderResult = Pogoprotos.Data.Logs.CatchPokemonLogEntry()
        return self
      }
      override public func clone() throws -> Pogoprotos.Data.Logs.CatchPokemonLogEntry.Builder {
        return try Pogoprotos.Data.Logs.CatchPokemonLogEntry.builderWithPrototype(builderResult)
      }
      override public func build() throws -> Pogoprotos.Data.Logs.CatchPokemonLogEntry {
           try checkInitialized()
           return buildPartial()
      }
      public func buildPartial() -> Pogoprotos.Data.Logs.CatchPokemonLogEntry {
        let returnMe:Pogoprotos.Data.Logs.CatchPokemonLogEntry = builderResult
        return returnMe
      }
      public func mergeFrom(other:Pogoprotos.Data.Logs.CatchPokemonLogEntry) throws -> Pogoprotos.Data.Logs.CatchPokemonLogEntry.Builder {
        if other == Pogoprotos.Data.Logs.CatchPokemonLogEntry() {
         return self
        }
        if other.hasResult {
             result = other.result
        }
        if other.hasPokemonId {
             pokemonId = other.pokemonId
        }
        if other.hasCombatPoints {
             combatPoints = other.combatPoints
        }
        if other.hasPokemonDataId {
             pokemonDataId = other.pokemonDataId
        }
        try mergeUnknownFields(other.unknownFields)
        return self
      }
      override public func mergeFromCodedInputStream(input:CodedInputStream) throws -> Pogoprotos.Data.Logs.CatchPokemonLogEntry.Builder {
           return try mergeFromCodedInputStream(input, extensionRegistry:ExtensionRegistry())
      }
      override public func mergeFromCodedInputStream(input:CodedInputStream, extensionRegistry:ExtensionRegistry) throws -> Pogoprotos.Data.Logs.CatchPokemonLogEntry.Builder {
        let unknownFieldsBuilder:UnknownFieldSet.Builder = try UnknownFieldSet.builderWithUnknownFields(self.unknownFields)
        while (true) {
          let protobufTag = try input.readTag()
          switch protobufTag {
          case 0: 
            self.unknownFields = try unknownFieldsBuilder.build()
            return self

          case 8:
            let valueIntresult = try input.readEnum()
            if let enumsresult = Pogoprotos.Data.Logs.CatchPokemonLogEntry.Result(rawValue:valueIntresult){
                 result = enumsresult
            } else {
                 try unknownFieldsBuilder.mergeVarintField(1, value:Int64(valueIntresult))
            }

          case 16:
            let valueIntpokemonId = try input.readEnum()
            if let enumspokemonId = Pogoprotos.Enums.PokemonId(rawValue:valueIntpokemonId){
                 pokemonId = enumspokemonId
            } else {
                 try unknownFieldsBuilder.mergeVarintField(2, value:Int64(valueIntpokemonId))
            }

          case 24:
            combatPoints = try input.readInt32()

          case 32:
            pokemonDataId = try input.readUInt64()

          default:
            if (!(try parseUnknownField(input,unknownFields:unknownFieldsBuilder, extensionRegistry:extensionRegistry, tag:protobufTag))) {
               unknownFields = try unknownFieldsBuilder.build()
               return self
            }
          }
        }
      }
      override class public func decodeToBuilder(jsonMap:Dictionary<String,AnyObject>) throws -> Pogoprotos.Data.Logs.CatchPokemonLogEntry.Builder {
        let resultDecodedBuilder = Pogoprotos.Data.Logs.CatchPokemonLogEntry.Builder()
        if let jsonValueResult = jsonMap["result"] as? String {
          resultDecodedBuilder.result = try Pogoprotos.Data.Logs.CatchPokemonLogEntry.Result.fromString(jsonValueResult)
        }
        if let jsonValuePokemonId = jsonMap["pokemonId"] as? String {
          resultDecodedBuilder.pokemonId = try Pogoprotos.Enums.PokemonId.fromString(jsonValuePokemonId)
        }
        if let jsonValueCombatPoints = jsonMap["combatPoints"] as? NSNumber {
          resultDecodedBuilder.combatPoints = jsonValueCombatPoints.intValue
        }
        if let jsonValuePokemonDataId = jsonMap["pokemonDataId"] as? String {
          resultDecodedBuilder.pokemonDataId = UInt64(jsonValuePokemonDataId)!
        }
        return resultDecodedBuilder
      }
      override class public func fromJSONToBuilder(data:NSData) throws -> Pogoprotos.Data.Logs.CatchPokemonLogEntry.Builder {
        let jsonData = try NSJSONSerialization.JSONObjectWithData(data, options: NSJSONReadingOptions(rawValue: 0))
        guard let jsDataCast = jsonData as? Dictionary<String,AnyObject> else {
          throw ProtocolBuffersError.InvalidProtocolBuffer("Invalid JSON data")
        }
        return try Pogoprotos.Data.Logs.CatchPokemonLogEntry.Builder.decodeToBuilder(jsDataCast)
      }
    }

  }

  final public class FortSearchLogEntry : GeneratedMessage, GeneratedMessageProtocol {


      //Enum type declaration start 

      public enum Result:Int32, CustomDebugStringConvertible, CustomStringConvertible {
        case Unset = 0
        case Success = 1
        public func toString() -> String {
          switch self {
          case .Unset: return "UNSET"
          case .Success: return "SUCCESS"
          }
        }
        public static func fromString(str:String) throws -> Pogoprotos.Data.Logs.FortSearchLogEntry.Result {
          switch str {
          case "UNSET":  return .Unset
          case "SUCCESS":  return .Success
          default: throw ProtocolBuffersError.InvalidProtocolBuffer("Conversion String to Enum has failed.")
          }
        }
        public var debugDescription:String { return getDescription() }
        public var description:String { return getDescription() }
        private func getDescription() -> String { 
            switch self {
                case .Unset: return ".Unset"
                case .Success: return ".Success"
            }
        }
      }

      //Enum type declaration end 

    public private(set) var result:Pogoprotos.Data.Logs.FortSearchLogEntry.Result = Pogoprotos.Data.Logs.FortSearchLogEntry.Result.Unset
    public private(set) var hasResult:Bool = false
    public private(set) var hasFortId:Bool = false
    public private(set) var fortId:String = ""

    public private(set) var items:Array<Pogoprotos.Inventory.Item.ItemData>  = Array<Pogoprotos.Inventory.Item.ItemData>()
    public private(set) var hasEggs:Bool = false
    public private(set) var eggs:Int32 = Int32(0)

    required public init() {
         super.init()
    }
    override public func isInitialized() -> Bool {
     return true
    }
    override public func writeToCodedOutputStream(output:CodedOutputStream) throws {
      if hasResult {
        try output.writeEnum(1, value:result.rawValue)
      }
      if hasFortId {
        try output.writeString(2, value:fortId)
      }
      for oneElementItems in items {
          try output.writeMessage(3, value:oneElementItems)
      }
      if hasEggs {
        try output.writeInt32(4, value:eggs)
      }
      try unknownFields.writeToCodedOutputStream(output)
    }
    override public func serializedSize() -> Int32 {
      var serialize_size:Int32 = memoizedSerializedSize
      if serialize_size != -1 {
       return serialize_size
      }

      serialize_size = 0
      if (hasResult) {
        serialize_size += result.rawValue.computeEnumSize(1)
      }
      if hasFortId {
        serialize_size += fortId.computeStringSize(2)
      }
      for oneElementItems in items {
          serialize_size += oneElementItems.computeMessageSize(3)
      }
      if hasEggs {
        serialize_size += eggs.computeInt32Size(4)
      }
      serialize_size += unknownFields.serializedSize()
      memoizedSerializedSize = serialize_size
      return serialize_size
    }
    public class func parseArrayDelimitedFromInputStream(input:NSInputStream) throws -> Array<Pogoprotos.Data.Logs.FortSearchLogEntry> {
      var mergedArray = Array<Pogoprotos.Data.Logs.FortSearchLogEntry>()
      while let value = try parseFromDelimitedFromInputStream(input) {
        mergedArray += [value]
      }
      return mergedArray
    }
    public class func parseFromDelimitedFromInputStream(input:NSInputStream) throws -> Pogoprotos.Data.Logs.FortSearchLogEntry? {
      return try Pogoprotos.Data.Logs.FortSearchLogEntry.Builder().mergeDelimitedFromInputStream(input)?.build()
    }
    public class func parseFromData(data:NSData) throws -> Pogoprotos.Data.Logs.FortSearchLogEntry {
      return try Pogoprotos.Data.Logs.FortSearchLogEntry.Builder().mergeFromData(data, extensionRegistry:Pogoprotos.Data.Logs.PogoprotosDataLogsRoot.sharedInstance.extensionRegistry).build()
    }
    public class func parseFromData(data:NSData, extensionRegistry:ExtensionRegistry) throws -> Pogoprotos.Data.Logs.FortSearchLogEntry {
      return try Pogoprotos.Data.Logs.FortSearchLogEntry.Builder().mergeFromData(data, extensionRegistry:extensionRegistry).build()
    }
    public class func parseFromInputStream(input:NSInputStream) throws -> Pogoprotos.Data.Logs.FortSearchLogEntry {
      return try Pogoprotos.Data.Logs.FortSearchLogEntry.Builder().mergeFromInputStream(input).build()
    }
    public class func parseFromInputStream(input:NSInputStream, extensionRegistry:ExtensionRegistry) throws -> Pogoprotos.Data.Logs.FortSearchLogEntry {
      return try Pogoprotos.Data.Logs.FortSearchLogEntry.Builder().mergeFromInputStream(input, extensionRegistry:extensionRegistry).build()
    }
    public class func parseFromCodedInputStream(input:CodedInputStream) throws -> Pogoprotos.Data.Logs.FortSearchLogEntry {
      return try Pogoprotos.Data.Logs.FortSearchLogEntry.Builder().mergeFromCodedInputStream(input).build()
    }
    public class func parseFromCodedInputStream(input:CodedInputStream, extensionRegistry:ExtensionRegistry) throws -> Pogoprotos.Data.Logs.FortSearchLogEntry {
      return try Pogoprotos.Data.Logs.FortSearchLogEntry.Builder().mergeFromCodedInputStream(input, extensionRegistry:extensionRegistry).build()
    }
    public class func getBuilder() -> Pogoprotos.Data.Logs.FortSearchLogEntry.Builder {
      return Pogoprotos.Data.Logs.FortSearchLogEntry.classBuilder() as! Pogoprotos.Data.Logs.FortSearchLogEntry.Builder
    }
    public func getBuilder() -> Pogoprotos.Data.Logs.FortSearchLogEntry.Builder {
      return classBuilder() as! Pogoprotos.Data.Logs.FortSearchLogEntry.Builder
    }
    override public class func classBuilder() -> MessageBuilder {
      return Pogoprotos.Data.Logs.FortSearchLogEntry.Builder()
    }
    override public func classBuilder() -> MessageBuilder {
      return Pogoprotos.Data.Logs.FortSearchLogEntry.Builder()
    }
    public func toBuilder() throws -> Pogoprotos.Data.Logs.FortSearchLogEntry.Builder {
      return try Pogoprotos.Data.Logs.FortSearchLogEntry.builderWithPrototype(self)
    }
    public class func builderWithPrototype(prototype:Pogoprotos.Data.Logs.FortSearchLogEntry) throws -> Pogoprotos.Data.Logs.FortSearchLogEntry.Builder {
      return try Pogoprotos.Data.Logs.FortSearchLogEntry.Builder().mergeFrom(prototype)
    }
    override public func encode() throws -> Dictionary<String,AnyObject> {
      guard isInitialized() else {
        throw ProtocolBuffersError.InvalidProtocolBuffer("Uninitialized Message")
      }

      var jsonMap:Dictionary<String,AnyObject> = Dictionary<String,AnyObject>()
      if hasResult {
        jsonMap["result"] = result.toString()
      }
      if hasFortId {
        jsonMap["fortId"] = fortId
      }
      if !items.isEmpty {
        var jsonArrayItems:Array<Dictionary<String,AnyObject>> = []
          for oneValueItems in items {
            let ecodedMessageItems = try oneValueItems.encode()
            jsonArrayItems += [ecodedMessageItems]
          }
        jsonMap["items"] = jsonArrayItems
      }
      if hasEggs {
        jsonMap["eggs"] = NSNumber(int:eggs)
      }
      return jsonMap
    }
    override class public func decode(jsonMap:Dictionary<String,AnyObject>) throws -> Pogoprotos.Data.Logs.FortSearchLogEntry {
      return try Pogoprotos.Data.Logs.FortSearchLogEntry.Builder.decodeToBuilder(jsonMap).build()
    }
    override class public func fromJSON(data:NSData) throws -> Pogoprotos.Data.Logs.FortSearchLogEntry {
      return try Pogoprotos.Data.Logs.FortSearchLogEntry.Builder.fromJSONToBuilder(data).build()
    }
    override public func getDescription(indent:String) throws -> String {
      var output = ""
      if (hasResult) {
        output += "\(indent) result: \(result.description)\n"
      }
      if hasFortId {
        output += "\(indent) fortId: \(fortId) \n"
      }
      var itemsElementIndex:Int = 0
      for oneElementItems in items {
          output += "\(indent) items[\(itemsElementIndex)] {\n"
          output += try oneElementItems.getDescription("\(indent)  ")
          output += "\(indent)}\n"
          itemsElementIndex += 1
      }
      if hasEggs {
        output += "\(indent) eggs: \(eggs) \n"
      }
      output += unknownFields.getDescription(indent)
      return output
    }
    override public var hashValue:Int {
        get {
            var hashCode:Int = 7
            if hasResult {
               hashCode = (hashCode &* 31) &+ Int(result.rawValue)
            }
            if hasFortId {
               hashCode = (hashCode &* 31) &+ fortId.hashValue
            }
            for oneElementItems in items {
                hashCode = (hashCode &* 31) &+ oneElementItems.hashValue
            }
            if hasEggs {
               hashCode = (hashCode &* 31) &+ eggs.hashValue
            }
            hashCode = (hashCode &* 31) &+  unknownFields.hashValue
            return hashCode
        }
    }


    //Meta information declaration start

    override public class func className() -> String {
        return "Pogoprotos.Data.Logs.FortSearchLogEntry"
    }
    override public func className() -> String {
        return "Pogoprotos.Data.Logs.FortSearchLogEntry"
    }
    override public func classMetaType() -> GeneratedMessage.Type {
        return Pogoprotos.Data.Logs.FortSearchLogEntry.self
    }
    //Meta information declaration end

    final public class Builder : GeneratedMessageBuilder {
      private var builderResult:Pogoprotos.Data.Logs.FortSearchLogEntry = Pogoprotos.Data.Logs.FortSearchLogEntry()
      public func getMessage() -> Pogoprotos.Data.Logs.FortSearchLogEntry {
          return builderResult
      }

      required override public init () {
         super.init()
      }
        public var hasResult:Bool{
            get {
                return builderResult.hasResult
            }
        }
        public var result:Pogoprotos.Data.Logs.FortSearchLogEntry.Result {
            get {
                return builderResult.result
            }
            set (value) {
                builderResult.hasResult = true
                builderResult.result = value
            }
        }
        public func setResult(value:Pogoprotos.Data.Logs.FortSearchLogEntry.Result) -> Pogoprotos.Data.Logs.FortSearchLogEntry.Builder {
          self.result = value
          return self
        }
        public func clearResult() -> Pogoprotos.Data.Logs.FortSearchLogEntry.Builder {
           builderResult.hasResult = false
           builderResult.result = .Unset
           return self
        }
      public var hasFortId:Bool {
           get {
                return builderResult.hasFortId
           }
      }
      public var fortId:String {
           get {
                return builderResult.fortId
           }
           set (value) {
               builderResult.hasFortId = true
               builderResult.fortId = value
           }
      }
      public func setFortId(value:String) -> Pogoprotos.Data.Logs.FortSearchLogEntry.Builder {
        self.fortId = value
        return self
      }
      public func clearFortId() -> Pogoprotos.Data.Logs.FortSearchLogEntry.Builder{
           builderResult.hasFortId = false
           builderResult.fortId = ""
           return self
      }
      public var items:Array<Pogoprotos.Inventory.Item.ItemData> {
           get {
               return builderResult.items
           }
           set (value) {
               builderResult.items = value
           }
      }
      public func setItems(value:Array<Pogoprotos.Inventory.Item.ItemData>) -> Pogoprotos.Data.Logs.FortSearchLogEntry.Builder {
        self.items = value
        return self
      }
      public func clearItems() -> Pogoprotos.Data.Logs.FortSearchLogEntry.Builder {
        builderResult.items.removeAll(keepCapacity: false)
        return self
      }
      public var hasEggs:Bool {
           get {
                return builderResult.hasEggs
           }
      }
      public var eggs:Int32 {
           get {
                return builderResult.eggs
           }
           set (value) {
               builderResult.hasEggs = true
               builderResult.eggs = value
           }
      }
      public func setEggs(value:Int32) -> Pogoprotos.Data.Logs.FortSearchLogEntry.Builder {
        self.eggs = value
        return self
      }
      public func clearEggs() -> Pogoprotos.Data.Logs.FortSearchLogEntry.Builder{
           builderResult.hasEggs = false
           builderResult.eggs = Int32(0)
           return self
      }
      override public var internalGetResult:GeneratedMessage {
           get {
              return builderResult
           }
      }
      override public func clear() -> Pogoprotos.Data.Logs.FortSearchLogEntry.Builder {
        builderResult = Pogoprotos.Data.Logs.FortSearchLogEntry()
        return self
      }
      override public func clone() throws -> Pogoprotos.Data.Logs.FortSearchLogEntry.Builder {
        return try Pogoprotos.Data.Logs.FortSearchLogEntry.builderWithPrototype(builderResult)
      }
      override public func build() throws -> Pogoprotos.Data.Logs.FortSearchLogEntry {
           try checkInitialized()
           return buildPartial()
      }
      public func buildPartial() -> Pogoprotos.Data.Logs.FortSearchLogEntry {
        let returnMe:Pogoprotos.Data.Logs.FortSearchLogEntry = builderResult
        return returnMe
      }
      public func mergeFrom(other:Pogoprotos.Data.Logs.FortSearchLogEntry) throws -> Pogoprotos.Data.Logs.FortSearchLogEntry.Builder {
        if other == Pogoprotos.Data.Logs.FortSearchLogEntry() {
         return self
        }
        if other.hasResult {
             result = other.result
        }
        if other.hasFortId {
             fortId = other.fortId
        }
        if !other.items.isEmpty  {
           builderResult.items += other.items
        }
        if other.hasEggs {
             eggs = other.eggs
        }
        try mergeUnknownFields(other.unknownFields)
        return self
      }
      override public func mergeFromCodedInputStream(input:CodedInputStream) throws -> Pogoprotos.Data.Logs.FortSearchLogEntry.Builder {
           return try mergeFromCodedInputStream(input, extensionRegistry:ExtensionRegistry())
      }
      override public func mergeFromCodedInputStream(input:CodedInputStream, extensionRegistry:ExtensionRegistry) throws -> Pogoprotos.Data.Logs.FortSearchLogEntry.Builder {
        let unknownFieldsBuilder:UnknownFieldSet.Builder = try UnknownFieldSet.builderWithUnknownFields(self.unknownFields)
        while (true) {
          let protobufTag = try input.readTag()
          switch protobufTag {
          case 0: 
            self.unknownFields = try unknownFieldsBuilder.build()
            return self

          case 8:
            let valueIntresult = try input.readEnum()
            if let enumsresult = Pogoprotos.Data.Logs.FortSearchLogEntry.Result(rawValue:valueIntresult){
                 result = enumsresult
            } else {
                 try unknownFieldsBuilder.mergeVarintField(1, value:Int64(valueIntresult))
            }

          case 18:
            fortId = try input.readString()

          case 26:
            let subBuilder = Pogoprotos.Inventory.Item.ItemData.Builder()
            try input.readMessage(subBuilder,extensionRegistry:extensionRegistry)
            items += [subBuilder.buildPartial()]

          case 32:
            eggs = try input.readInt32()

          default:
            if (!(try parseUnknownField(input,unknownFields:unknownFieldsBuilder, extensionRegistry:extensionRegistry, tag:protobufTag))) {
               unknownFields = try unknownFieldsBuilder.build()
               return self
            }
          }
        }
      }
      override class public func decodeToBuilder(jsonMap:Dictionary<String,AnyObject>) throws -> Pogoprotos.Data.Logs.FortSearchLogEntry.Builder {
        let resultDecodedBuilder = Pogoprotos.Data.Logs.FortSearchLogEntry.Builder()
        if let jsonValueResult = jsonMap["result"] as? String {
          resultDecodedBuilder.result = try Pogoprotos.Data.Logs.FortSearchLogEntry.Result.fromString(jsonValueResult)
        }
        if let jsonValueFortId = jsonMap["fortId"] as? String {
          resultDecodedBuilder.fortId = jsonValueFortId
        }
        if let jsonValueItems = jsonMap["items"] as? Array<Dictionary<String,AnyObject>> {
          var jsonArrayItems:Array<Pogoprotos.Inventory.Item.ItemData> = []
          for oneValueItems in jsonValueItems {
            let messageFromStringItems = try Pogoprotos.Inventory.Item.ItemData.Builder.decodeToBuilder(oneValueItems).build()

            jsonArrayItems += [messageFromStringItems]
          }
          resultDecodedBuilder.items = jsonArrayItems
        }
        if let jsonValueEggs = jsonMap["eggs"] as? NSNumber {
          resultDecodedBuilder.eggs = jsonValueEggs.intValue
        }
        return resultDecodedBuilder
      }
      override class public func fromJSONToBuilder(data:NSData) throws -> Pogoprotos.Data.Logs.FortSearchLogEntry.Builder {
        let jsonData = try NSJSONSerialization.JSONObjectWithData(data, options: NSJSONReadingOptions(rawValue: 0))
        guard let jsDataCast = jsonData as? Dictionary<String,AnyObject> else {
          throw ProtocolBuffersError.InvalidProtocolBuffer("Invalid JSON data")
        }
        return try Pogoprotos.Data.Logs.FortSearchLogEntry.Builder.decodeToBuilder(jsDataCast)
      }
    }

  }

}

// @@protoc_insertion_point(global_scope)
