// Generated by the Protocol Buffers 3.0 compiler.  DO NOT EDIT!
// Source file "POGOProtos.Networking.Platform.proto"
// Syntax "Proto3"

import Foundation
import ProtocolBuffers


public extension Pogoprotos.Networking.Platform {
  public struct PogoprotosNetworkingPlatformRoot {
    public static var sharedInstance : PogoprotosNetworkingPlatformRoot {
     struct Static {
         static let instance : PogoprotosNetworkingPlatformRoot = PogoprotosNetworkingPlatformRoot()
     }
     return Static.instance
    }
    public var extensionRegistry:ExtensionRegistry

    init() {
      extensionRegistry = ExtensionRegistry()
      registerAllExtensions(extensionRegistry)
    }
    public func registerAllExtensions(registry:ExtensionRegistry) {
    }
  }



  //Enum type declaration start 

  public enum PlatformRequestType:Int32, CustomDebugStringConvertible, CustomStringConvertible {
    case MethodUnset = 0
    case BuyItemPokecoins = 2
    case BuyItemAndroid = 3
    case BuyItemIos = 4
    case GetStoreItems = 5
    case SendEncryptedSignature = 6
    public func toString() -> String {
      switch self {
      case .MethodUnset: return "METHOD_UNSET"
      case .BuyItemPokecoins: return "BUY_ITEM_POKECOINS"
      case .BuyItemAndroid: return "BUY_ITEM_ANDROID"
      case .BuyItemIos: return "BUY_ITEM_IOS"
      case .GetStoreItems: return "GET_STORE_ITEMS"
      case .SendEncryptedSignature: return "SEND_ENCRYPTED_SIGNATURE"
      }
    }
    public static func fromString(str:String) throws -> Pogoprotos.Networking.Platform.PlatformRequestType {
      switch str {
      case "METHOD_UNSET":  return .MethodUnset
      case "BUY_ITEM_POKECOINS":  return .BuyItemPokecoins
      case "BUY_ITEM_ANDROID":  return .BuyItemAndroid
      case "BUY_ITEM_IOS":  return .BuyItemIos
      case "GET_STORE_ITEMS":  return .GetStoreItems
      case "SEND_ENCRYPTED_SIGNATURE":  return .SendEncryptedSignature
      default: throw ProtocolBuffersError.InvalidProtocolBuffer("Conversion String to Enum has failed.")
      }
    }
    public var debugDescription:String { return getDescription() }
    public var description:String { return getDescription() }
    private func getDescription() -> String { 
        switch self {
            case .MethodUnset: return ".MethodUnset"
            case .BuyItemPokecoins: return ".BuyItemPokecoins"
            case .BuyItemAndroid: return ".BuyItemAndroid"
            case .BuyItemIos: return ".BuyItemIos"
            case .GetStoreItems: return ".GetStoreItems"
            case .SendEncryptedSignature: return ".SendEncryptedSignature"
        }
    }
  }

  //Enum type declaration end 

}

// @@protoc_insertion_point(global_scope)
